-created login page
vaniprasad97/social-media pull request #2
Opened 2022-01-25 08:48 UTC by vaniprasad97

- validate user login data

2022-01-27 04:00 UTC, dheeraj-murali requested changes
Overall, really happy with what you guys have done 👏. Few things to correct, I wouldn't call them mistakes, take 'em as improvements.

2022-01-27 04:00 UTC, dheeraj-murali commented on public/manifest.json
> -      "sizes": "512x512"
It's always better to replace the icons than remove it completely. It helps users identify your website easily, gives a better user experience

2022-01-27 04:00 UTC, dheeraj-murali commented on src/App.js
> +import "./styles/LoginPage.css"
If the contents of this is only being used in login page; Ideally it should be that way, then move this to login page.

2022-01-27 04:00 UTC, dheeraj-murali commented on src/pages/LoginPage.js
> +  const history = useNavigate();
as per the documentation The `useNavigate` hook returns a function that lets you navigate programmatically and not a browser history. rename this `const` to **navigate**. better for readability. 

https://reactrouter.com/docs/en/v6/api#usenavigate

2022-01-27 04:00 UTC, dheeraj-murali commented on src/pages/LoginPage.js
> +          type="text"
HTML supports a lot of different input types. Since we know it's an email filed. adding the type email will give you browser validation and better accessibility.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

2022-01-27 04:00 UTC, dheeraj-murali commented on src/pages/LoginPage.js
> +        <p>{formErrors.passWord}</p>
There is field set element in HTML where you can combine labels, inputs and errors. wrap these in it.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

2022-01-27 04:00 UTC, dheeraj-murali commented on src/pages/LoginPage.js
> +  };
It's a good thing that you have abstracted the validation logic into a different function. You should be doing this more often.

2 things to note here

1. Make sure your abstraction do only one thing.

> Here, validate function is validating the form + navigating to the next page. these two things should be kept separate. validate function should only validate and give you back the error details or a Boolean saying the form is valid or not.  

2. try to move as many of the abstraction out of the react component.

2022-01-27 04:00 UTC, dheeraj-murali commented on src/styles/LoginPage.css
> +  display: flex;
add an empty line after each logical contents, please

2022-01-27 04:00 UTC, dheeraj-murali commented on src/pages/LoginPage.js
> +      }
a general rule in username and password validation is that, **You don't tell user which one is wrong**. This is for security. Keep them guessing.

2022-01-27 06:21 UTC, vaniprasad97 commented on src/App.js
> +import "./styles/LoginPage.css"
resolved

2022-01-27 06:21 UTC, vaniprasad97 commented on src/pages/LoginPage.js
> +  const history = useNavigate();
resolved

2022-01-27 06:22 UTC, vaniprasad97 commented on src/pages/LoginPage.js
> +          type="text"
resolved

2022-01-27 07:34 UTC, vaniprasad97 commented on public/manifest.json
> -      "sizes": "512x512"
resolved

2022-01-27 07:34 UTC, vaniprasad97 commented on src/pages/LoginPage.js
> +        <p>{formErrors.passWord}</p>
resolved

2022-01-27 07:37 UTC, vaniprasad97 commented on src/pages/LoginPage.js
> +  };
resolved

2022-01-27 07:47 UTC, vaniprasad97 commented on src/styles/LoginPage.css
> +  display: flex;
resolved

2022-01-27 07:47 UTC, vaniprasad97 commented on src/pages/LoginPage.js
> +      }
resolved

2022-01-28 03:58 UTC, dheeraj-murali approved these changes

2022-01-28 04:07 UTC, merged